# Hierarchy for settings source goes in this order:
# 1. Environment variables
# 2. config.toml (this very file)
# 3. server.properties
# 4. Hard-coded defaults

[watchdog]
delay = 10 # delay in seconds before trying to start the Minecraft server again. If set to 0, disables the watchdog.

# Launch settings
[launch_settings]
server_directory = "" # relative working directory of the server, it is adviced to use this instead of defining it in the launch command
launch_command = "" # command for launching the Minecraft server

# You can use this section to override server.properties settings and the default Minecraft version
[server_properties]
#server_version = "1.21.4"
#server_ip = "0.0.0.0"
#server_port = 25565
#server_motd = "A Minecraft Server"
#max_players = 20